### ISSUE TITLE
Run workflow to completion

### ISSUE THREAD

**Issue by ByrCWollam** [Bayer-Group/BayerCLAW#10]
I would like to have an option to indicate that a workflow should run through all steps even if a step fails, and then record whether the workflow failed or was successful. The reason for this is that some steps in my workflow are independent of other steps and therefore could be run even if a step on which they do not depend failed. This could be realized by having a template like:
```
params:
    ...
    run_to_completion: true
steps:
    - step1:
        ...
        commands:
            - run_step1
    - step2:
        ...
        depends_on:
            - step1
        commands:
            - run_step2
    - step3:
        ...
        depends_on:
            - step1
            - step2
        commands:
            - run_step3
    - step4:
        ...
        commands:
            - run_step4
```

The compiler could add an optional step to the workflow at a user defined location to handle the workflows status. That step would fail, i.e. the step function execution would terminate at that location and would show a status of Failed, if any of the steps failed. Perhaps the user could indicate the location with a template format like:
```
steps:
    ...
    - HandleStatus
        Type: RunToCompletionHandler
    - AnotherStepThatIsOnlyExecutedIfHandleStatusSucceeds:
        ...
```

Further I would want to be able to retrieve the step status data. For instance if in the above workflow step1 was successful, step2 failed, step3 didn't get executed because of its dependency on step2, and step4 was successful, then I'd like to retrieve that, perhaps from a JSON file under the repository S3 location. In this scenario step1 and step4 would have status PASS, step2 would have status FAIL, and step3 would have status SKIP, or something to that affect. Even better I'd like to have the framework initialize the status of all steps in the workflow to READY at the beginning, that way if the user is inspecting the workflows execution information they'd be able to see that not all steps have been processed yet as noted by some having a READY status.
